// Single source of truth for the lo-fi design book (PDF) and the prototype's "All screens" page.
// Each screen spec renders the real prototype at `url` as `role`, so the PDF always matches the app.

export const ROLE_LABEL = { guest: 'Visitor', pet: 'Pet', human: 'Human', admin: 'Admin' }

export const MODULES = [
  { no: 1, key: 'auth', prefix: 'AU', name: 'Authentication & Verification',
    desc: 'Sign-up, sign-in and the admin verification gate. Every new Pet and Human account starts as Pending Verification and cannot use the platform until an admin approves it.',
    roles: { Human: 'Sign up, submit ID', Pet: 'Sign up, submit caretaker ID', Admin: 'Approve / deny' } },
  { no: 2, key: 'profile', prefix: 'PR', name: 'Profile Management',
    desc: 'The two sides of every match: the pet’s résumé and the human’s Home Profile with the lifestyle quiz. Long forms are split into steps with a progress indicator.',
    roles: { Human: 'Home Profile & quiz', Pet: 'Résumé', Admin: 'Moderate' } },
  { no: 3, key: 'discovery', prefix: 'DS', name: 'Discovery & Search',
    desc: 'Browsing, filtering and searching. Humans find pets; pets find homes. Home Profiles show only public details — the city and a household summary.',
    roles: { Human: 'Browse pets', Pet: 'Browse homes', Admin: 'View all' } },
  { no: 4, key: 'matching', prefix: 'MT', name: 'Matching & Suggestions',
    desc: 'One compatibility score (0–100) used in both directions: Pets for You and Homes for You. Every match explains itself with its top reasons.',
    roles: { Human: 'Pets for You', Pet: 'Homes for You', Admin: '—' } },
  { no: 5, key: 'bookmarks', prefix: 'BM', name: 'Bookmarks',
    desc: 'Save pets or homes for later, like saving a job posting.',
    roles: { Human: 'Save pets', Pet: 'Save homes', Admin: '—' } },
  { no: 6, key: 'requests', prefix: 'RQ', name: 'Adoption Requests',
    desc: 'The pet’s job application. Humans may nudge with an Invite to Apply; the pet sends a request with a cover letter; the human approves or declines.',
    roles: { Human: 'Receive, approve / decline, invite', Pet: 'Send, track, withdraw', Admin: 'Monitor' } },
  { no: 7, key: 'meet', prefix: 'MG', name: 'Meet & Greet',
    desc: 'The interview. After approval the pet books one of the human’s slots, the human confirms, and after the meeting the human decides.',
    roles: { Human: 'Set slots, confirm, decide', Pet: 'Book, reschedule', Admin: 'Monitor' } },
  { no: 8, key: 'adoption', prefix: 'AL', name: 'Adoption & Alumni',
    desc: 'The job offer. Choosing Adopt makes the pet “Hired”, turns its profile into an alumni profile linked to the human, and gives the human the Furparent label.',
    roles: { Human: 'Adopt, become Furparent', Pet: 'Becomes alumni (Hired)', Admin: 'Resolve issues' } },
  { no: 9, key: 'notifications', prefix: 'NT', name: 'Notifications',
    desc: 'In-app notifications for requests, Meet & Greets, verification and announcements.',
    roles: { Human: 'Receive', Pet: 'Receive', Admin: 'Announcements' } },
  { no: 10, key: 'feed', prefix: 'FD', name: 'Community Feed & Stories',
    desc: 'One shuffled social feed for everyone: automatic “For Hire” posts, pet updates (also after adoption), human posts and adoption stories.',
    roles: { Human: 'Post, react, comment', Pet: 'Post updates', Admin: 'Moderate' } },
  { no: 11, key: 'reports', prefix: 'RP', name: 'Reports & Moderation',
    desc: 'Anyone active can report a profile, post, comment or account. Admins review and act, always with a reason.',
    roles: { Human: 'Report', Pet: 'Report', Admin: 'Review & act' } },
  { no: 12, key: 'accounts', prefix: 'AC', name: 'Account Administration',
    desc: 'Owners manage their own account settings. Admins suspend, reactivate or deactivate any account.',
    roles: { Human: 'Own account', Pet: 'Own account', Admin: 'All accounts' } },
  { no: 13, key: 'analytics', prefix: 'AN', name: 'Analytics',
    desc: 'Stats for each role: the pet’s views and requests, the human’s match and request history, and the admin’s platform dashboard.',
    roles: { Human: 'Match results, request history', Pet: 'Views, bookmarks, request stats', Admin: 'Platform dashboard' } },
  { no: 14, key: 'logs', prefix: 'LG', name: 'Activity Logs',
    desc: 'Who did what, when and why. Owners see their own activity; admins see the full, read-only log.',
    roles: { Human: 'Own activity', Pet: 'Own activity', Admin: 'Full logs' } },
]

const MOD = { GN: 'global', ...Object.fromEntries(MODULES.map((m) => [m.prefix, m.key])) }

function S(id, title, role, url, o = {}) {
  const kind = o.kind || 'Screen'
  return {
    id, title, role, url, kind,
    module: MOD[id.slice(0, 2)],
    viewport: o.viewport ?? kind !== 'Screen',
    acct: o.acct || 'Active',
    purpose: o.purpose || '',
    ui: o.ui || [],
    actions: o.actions || [],
    rules: o.rules || [],
    fr: o.fr || [],
  }
}

export const SCREENS = [
  /* ---------- Navigation & global ---------- */
  S('GN-01', 'Top navigation · Me menu open', 'pet', '/feed?menu=me', { kind: 'Dropdown',
    purpose: 'Global navigation for signed-in members. The Me menu collects profile, account and sign-out links.',
    ui: ['Logo → Home feed', 'Search box (pets, homes, posts)', 'Home · Homes for You · Browse · Requests · Alerts · Me', 'Unread count on Requests and Alerts', 'Me menu: profile card, résumé links, bookmarks, stats, activity, settings, log out'],
    actions: ['Search + Enter → DS-03 Search results', 'Alerts → NT-01 dropdown', 'Log out → AU-01 Landing'],
    rules: ['The Human variant shows “Pets for You” and Meet & Greet availability instead.'] }),
  S('GN-02', 'Page not found', 'human', '/profile/unknown', { kind: 'Error state',
    purpose: 'Shown for broken links and for profiles that are hidden, suspended or deactivated.',
    ui: ['Empty-state illustration', 'Short explanation', 'Browse and Back to feed buttons'],
    actions: ['Back to feed → FD-01'] }),

  /* ---------- 1 Authentication & Verification ---------- */
  S('AU-01', 'Landing page', 'guest', '/', {
    purpose: 'Public home page. Explains the job-hunting idea and sends visitors to the right sign-up.',
    ui: ['Guest top bar: How it works, Success stories, FAQ, Join now, Sign in', 'Hero with two sign-up buttons', 'How it works in 4 steps', 'Recently Hired alumni strip', 'Verification promise', 'Footer links'],
    actions: ['“I’m a pet…” → AU-08 Pet sign-up', '“I want to adopt” → AU-13 Human sign-up', 'Join now → AU-07', 'Sign in → AU-02'],
    fr: ['FR1', 'FR18'] }),
  S('AU-02', 'Sign in', 'guest', '/login', {
    purpose: 'One sign-in page for Pets, Humans and Admins.',
    ui: ['Email and password', 'Keep me signed in', 'Forgot password link', 'Sign in button', 'Join now link'],
    actions: ['Active → FD-01 / FD-02 feed (Admin → AN-03 dashboard)', 'Pending / Denied / Suspended → AU-18, AU-20, AU-21', 'Forgot password → AU-04'],
    rules: ['Role and account status are checked on the server; blocked accounts never reach member pages (NFR2).'],
    fr: ['FR2', 'FR19'] }),
  S('AU-03', 'Sign in · error', 'guest', '/login?error=credentials', { kind: 'Error state',
    purpose: 'Inline error after a failed sign-in.',
    ui: ['Error banner above the form', 'Typed email is kept'],
    actions: ['Try again', 'Forgot password → AU-04'],
    rules: ['After 5 failed tries, sign-in pauses for 15 minutes.', 'Deactivated accounts see “This account was closed.”'],
    fr: ['FR2', 'FR19'] }),
  S('AU-04', 'Forgot password', 'guest', '/forgot', {
    purpose: 'Starts a password reset by email.',
    ui: ['Email field', 'Send reset link', 'Back to sign in'],
    actions: ['Send reset link → AU-05'] }),
  S('AU-05', 'Reset link sent', 'guest', '/forgot?sent=1', { kind: 'State',
    purpose: 'Confirms the email was sent without revealing whether the account exists.',
    ui: ['Confirmation message', 'Link expiry (30 min)', 'Resend email', 'Back to sign in'],
    actions: ['Open the emailed link → AU-06'] }),
  S('AU-06', 'Set a new password', 'guest', '/reset', {
    purpose: 'Sets a new password from the emailed link.',
    ui: ['New password with strength meter', 'Confirm password', 'Save and sign in'],
    actions: ['Save → AU-02 with a “Password reset” toast'] }),
  S('AU-07', 'Join · choose account type', 'guest', '/signup', {
    purpose: 'Splits sign-up into the two public account types. Admin accounts are created by the system, not here.',
    ui: ['Two option cards: I’m a pet / I want to adopt', 'Sign in link'],
    actions: ['I’m a pet → AU-08', 'I want to adopt → AU-13'],
    fr: ['FR1', 'FR18'] }),
  S('AU-08', 'Pet sign-up · 1 Account', 'guest', '/signup/pet?step=1', {
    purpose: 'Step 1 of 5. The caretaker creates the pet’s login.',
    ui: ['5-step progress indicator', 'Email, password, confirm password', 'Back / Next'],
    actions: ['Next → AU-09'],
    rules: ['Long forms are split into steps with a progress indicator (NFR1).'],
    fr: ['FR18'] }),
  S('AU-09', 'Pet sign-up · 2 Pet details', 'guest', '/signup/pet?step=2', {
    purpose: 'Step 2 of 5. Basic facts the admin will check.',
    ui: ['Name, species, breed, approximate age', 'Where the pet is staying', 'City / province'],
    actions: ['Next → AU-10', 'Back → AU-08'],
    rules: ['Name, species, breed and age are locked after approval.'],
    fr: ['FR18'] }),
  S('AU-10', 'Pet sign-up · 3 Photo', 'guest', '/signup/pet?step=3', {
    purpose: 'Step 3 of 5. At least one clear photo is required.',
    ui: ['Upload area (JPG, PNG, PDF · 5 MB)', 'Uploaded thumbnails'],
    actions: ['Next → AU-11'],
    fr: ['FR18'] }),
  S('AU-11', 'Pet sign-up · 4 Caretaker & ID', 'guest', '/signup/pet?step=4', {
    purpose: 'Step 4 of 5. The caretaker is the person the admin verifies.',
    ui: ['Caretaker name and contact number', 'Valid ID upload', 'Vet record / shelter certificate (optional)'],
    actions: ['Next → AU-12'],
    rules: ['Documents are visible to admins only (NFR4).'],
    fr: ['FR18'] }),
  S('AU-12', 'Pet sign-up · 5 Review', 'guest', '/signup/pet?step=5', {
    purpose: 'Step 5 of 5. Review and submit for verification.',
    ui: ['Summary of all details', 'Edit details', 'Terms & guidelines checkbox', 'Submit for verification'],
    actions: ['Submit → account is Pending Verification → AU-18'],
    fr: ['FR18'] }),
  S('AU-13', 'Human sign-up · 1 Account', 'guest', '/signup/human?step=1', {
    purpose: 'Step 1 of 5. The adopter creates a login.',
    ui: ['5-step progress indicator', 'Email, password, confirm password'],
    actions: ['Next → AU-14'],
    fr: ['FR1'] }),
  S('AU-14', 'Human sign-up · 2 Personal details', 'guest', '/signup/human?step=2', {
    purpose: 'Step 2 of 5. Identity details the admin checks against the ID.',
    ui: ['Full name', 'Birthdate (18 or older)', 'Contact number'],
    actions: ['Next → AU-15'],
    rules: ['Under-18 birthdates can’t continue.', 'The phone number is shared only after a Meet & Greet is confirmed.'],
    fr: ['FR1'] }),
  S('AU-15', 'Human sign-up · 3 Address', 'guest', '/signup/human?step=3', {
    purpose: 'Step 3 of 5. Location for matching; only the city is public.',
    ui: ['City, province, street address'],
    actions: ['Next → AU-16'],
    rules: ['Matches are limited to the same province.'],
    fr: ['FR1'] }),
  S('AU-16', 'Human sign-up · 4 Valid ID', 'guest', '/signup/human?step=4', {
    purpose: 'Step 4 of 5. A photo of a valid ID for the admin.',
    ui: ['ID type', 'ID photo upload'],
    actions: ['Next → AU-17'],
    fr: ['FR1'] }),
  S('AU-17', 'Human sign-up · 5 Review', 'guest', '/signup/human?step=5', {
    purpose: 'Step 5 of 5. Review and submit.',
    ui: ['Summary', 'Terms checkbox', 'Submit for verification'],
    actions: ['Submit → Pending Verification → AU-18'],
    fr: ['FR1'] }),
  S('AU-18', 'Pending approval screen', 'pet', '/feed', { acct: 'Pending Verification',
    purpose: 'The only screen a pending account can use. It replaces the whole app until an admin decides.',
    ui: ['Minimal top bar: Help center, Log out', 'Status badge and explanation', 'Submitted details summary', 'Edit submitted details'],
    actions: ['Edit submitted details → AU-19', 'After approval, the next sign-in lands on the feed'],
    rules: ['Can’t browse, post, send or receive anything (Section 5.1).'],
    fr: ['FR2', 'FR19'] }),
  S('AU-19', 'Edit submitted details', 'pet', '/account/edit', { acct: 'Pending Verification',
    purpose: 'Lets a pending or denied account fix its details and resubmit.',
    ui: ['Editable details form', 'Current ID and a replace upload', 'Save and resubmit'],
    actions: ['Save → back to AU-18 with a toast; the account re-enters the queue'],
    fr: ['FR2', 'FR19'] }),
  S('AU-20', 'Account denied', 'human', '/feed', { acct: 'Denied',
    purpose: 'Shows the admin’s reason and a way to fix it.',
    ui: ['Denied badge', 'Reason from admin', 'Correct & resubmit'],
    actions: ['Correct & resubmit → AU-19 (status back to Pending)'],
    fr: ['FR2'] }),
  S('AU-21', 'Account suspended', 'pet', '/feed', { acct: 'Suspended',
    purpose: 'Suspended owners see only the reason. Their profile is hidden.',
    ui: ['Suspended badge', 'Reason', 'Contact support'],
    actions: ['Only an admin can reactivate (AC-09)'],
    fr: ['FR34'] }),
  S('AU-22', 'Admin · Verification queue', 'admin', '/admin/verification', {
    purpose: 'Every new Pet and Human account waiting for review, oldest first.',
    ui: ['Admin sidebar with queue count', 'Tabs: All / Pet / Human', 'Table: account, type, submitted, documents, status', 'Search by name'],
    actions: ['Review → AU-23 / AU-24'],
    fr: ['FR33'] }),
  S('AU-23', 'Admin · Review pet account', 'admin', '/admin/verification/v1', {
    purpose: 'Checks a pet account and its caretaker’s ID.',
    ui: ['Submitted details', 'Documents: ID, pet photo, vet record', 'Checklist', 'Approve / Deny…', 'Position in queue and Next'],
    actions: ['Approve → AU-26', 'Deny… → AU-25'],
    fr: ['FR33'] }),
  S('AU-24', 'Admin · Review human account (resubmitted)', 'admin', '/admin/verification/v4', {
    purpose: 'The same review for a human, showing the previous denial reason when an account was resubmitted.',
    ui: ['Resubmission alert with the previous reason', 'Identity details with 18+ check', 'ID document', 'Checklist and decision'],
    actions: ['Approve → AU-26', 'Deny… → AU-25'],
    fr: ['FR33'] }),
  S('AU-25', 'Admin · Deny account dialog', 'admin', '/admin/verification/v4?modal=deny', { kind: 'Dialog',
    purpose: 'A reason is required to deny. The owner sees it on AU-20.',
    ui: ['Reason options', 'Message to the owner', 'Cancel / Deny account'],
    actions: ['Deny → status Denied, owner notified, action logged'],
    fr: ['FR33'] }),
  S('AU-26', 'Admin · Account approved (toast)', 'admin', '/admin/verification/v1?result=Active&toast=approved', { kind: 'Toast',
    purpose: 'Confirmation after approving. The account becomes Active.',
    ui: ['Status badge now Active', 'Toast: owner notified'],
    actions: ['The owner can now use every feature for their role'],
    rules: ['Every decision is written to the activity log (NFR9).'],
    fr: ['FR33'] }),

  /* ---------- 2 Profile Management ---------- */
  S('PR-01', 'My résumé (owner view)', 'pet', '/me', {
    purpose: 'The pet’s LinkedIn-style profile as the pet sees it.',
    ui: ['Cover, photo, name, status badge', '“Currently at” line, like a workplace', 'Edit résumé, View stats, Share', 'About, Photos, Temperament, Skills', 'Compatibility & needs, Health', 'Profile strength, latest activity, similar pets'],
    actions: ['Edit résumé → PR-03', 'View stats → AN-01', 'Photo → DS-06 viewer'],
    rules: ['There is no status dropdown: the status changes only through the system (FR27).'],
    fr: ['FR20', 'FR27'] }),
  S('PR-02', 'Résumé in Draft', 'pet', '/me?draft=1', { kind: 'State',
    purpose: 'An approved pet whose résumé is incomplete. Drafts are hidden from search and matches.',
    ui: ['Draft banner listing what’s missing', 'Draft status badge', 'Continue editing'],
    actions: ['Continue editing → PR-07 (Health step)'],
    rules: ['Draft → Looking for a Home happens automatically on publish.'],
    fr: ['FR20', 'FR27'] }),
  S('PR-03', 'Edit résumé · 1 Basics', 'pet', '/resume/edit?step=1', {
    purpose: 'Step 1 of 6. Fields the admin verified are locked.',
    ui: ['6-step progress indicator', 'Locked: name, species, breed, age', 'Sex, size, Currently at, city', 'Back / Save draft / Next', 'Preview résumé'],
    actions: ['Next → PR-04'],
    rules: ['Locked fields change only through an admin request (AC-03).'],
    fr: ['FR20'] }),
  S('PR-04', 'Edit résumé · 2 Photos', 'pet', '/resume/edit?step=2', {
    purpose: 'Step 2 of 6. Three to ten photos; the first is the profile photo.',
    ui: ['Photo grid with Main / Remove / Move', 'Add photo tile', 'Cover photo upload'],
    actions: ['+ Add photo → PR-09 dialog'],
    fr: ['FR20'] }),
  S('PR-05', 'Edit résumé · 3 About & temperament', 'pet', '/resume/edit?step=3', {
    purpose: 'Step 3 of 6. Written in the pet’s own voice.',
    ui: ['First-person bio', 'Temperament tags (up to 5)', 'Energy level'],
    actions: ['Next → PR-06'],
    rules: ['Energy level feeds the match score (20 points).'],
    fr: ['FR20'] }),
  S('PR-06', 'Edit résumé · 4 Skills & compatibility', 'pet', '/resume/edit?step=4', {
    purpose: 'Step 4 of 6. The fields matched against the human’s quiz.',
    ui: ['Skills', 'Good with kids / dogs / cats: Yes, No, Unknown', 'Time alone, space needs, experience needed'],
    actions: ['Next → PR-07'],
    rules: ['A “No” becomes a dealbreaker in matching.'],
    fr: ['FR20'] }),
  S('PR-07', 'Edit résumé · 5 Health', 'pet', '/resume/edit?step=5', {
    purpose: 'Step 5 of 6. Health and vet notes.',
    ui: ['Health & vet notes', 'Special needs', 'Vet records upload (optional)'],
    actions: ['Next → PR-08'],
    fr: ['FR20'] }),
  S('PR-08', 'Edit résumé · 6 Review & publish', 'pet', '/resume/edit?step=6', {
    purpose: 'Step 6 of 6. Completion checklist and publish.',
    ui: ['Résumé summary card', 'Completion checklist', 'Publish résumé'],
    actions: ['Publish → PR-10'],
    fr: ['FR20', 'FR27'] }),
  S('PR-09', 'Add photo dialog', 'pet', '/resume/edit?step=2&modal=photo', { kind: 'Dialog',
    purpose: 'Upload, crop and caption a résumé photo.',
    ui: ['Drop zone', 'Crop preview', 'Caption', 'Use as gallery or profile photo'],
    actions: ['Add photo → toast, back to PR-04'],
    rules: ['Images are compressed on upload (NFR7).'],
    fr: ['FR20'] }),
  S('PR-10', 'Résumé published', 'pet', '/resume/edit?done=1', { kind: 'State',
    purpose: 'Confirms the résumé is live.',
    ui: ['Status change: Draft → Looking for a Home', 'Next-step buttons'],
    actions: ['See Homes for You → MT-02', 'See my For Hire post → FD-02'],
    rules: ['A “For Hire” post is added to the feed automatically.'],
    fr: ['FR20', 'FR27'] }),
  S('PR-11', 'My Home Profile (Furparent)', 'human', '/me', {
    purpose: 'The human’s side of the match. Pets read it like a job posting.',
    ui: ['Open to Adopt and Furparent badges', 'Edit Home Profile & quiz, Edit intro, Open to Adopt toggle', 'About, Household & space, Lifestyle, What we’re looking for', 'Adopted pets (Alumni) with Adoption details', 'Profile checklist and views'],
    actions: ['Edit Home Profile & quiz → PR-14', 'Edit intro → PR-12', 'Toggle off → PR-13', 'Adoption details → AL-06'],
    fr: ['FR3', 'FR4', 'FR13'] }),
  S('PR-12', 'Edit intro dialog', 'human', '/me?modal=intro', { kind: 'Dialog',
    purpose: 'Edits the top of the Home Profile.',
    ui: ['Cover and profile photo', 'Display name (locked)', 'Headline', 'About our home', 'City shown (locked)'],
    actions: ['Save → toast'],
    fr: ['FR3'] }),
  S('PR-13', 'Turn off Open to Adopt', 'human', '/me?modal=close', { kind: 'Dialog',
    purpose: 'Confirms what turning off Open to Adopt does.',
    ui: ['What happens list', 'Cancel / Turn off'],
    actions: ['Turn off → badge removed; no new requests'],
    rules: ['Requests already in progress continue (Section 5.5).'],
    fr: ['FR4'] }),
  S('PR-14', 'Home Profile & quiz · 1 Household', 'human', '/quiz?step=1', {
    purpose: 'Step 1 of 6 of the Home Profile and lifestyle quiz.',
    ui: ['6-step progress indicator', 'Who lives with you', 'Other pets at home', 'About your home'],
    actions: ['Next → PR-15'],
    rules: ['Kids and other pets drive the dealbreakers.'],
    fr: ['FR3'] }),
  S('PR-15', 'Home Profile & quiz · 2 Home & space', 'human', '/quiz?step=2', {
    purpose: 'Step 2 of 6.',
    ui: ['Home type', 'Outdoor space', 'City / province'],
    actions: ['Next → PR-16'],
    fr: ['FR3'] }),
  S('PR-16', 'Home Profile & quiz · 3 Lifestyle', 'human', '/quiz?step=3', {
    purpose: 'Step 3 of 6. The two answers with the most weight.',
    ui: ['Activity level', 'Hours away per day'],
    actions: ['Next → PR-17'],
    rules: ['Activity is worth 20 points, hours away 15.'],
    fr: ['FR3'] }),
  S('PR-17', 'Home Profile & quiz · 4 Experience', 'human', '/quiz?step=4', {
    purpose: 'Step 4 of 6.',
    ui: ['Pet experience', 'Willing to handle special needs'],
    actions: ['Next → PR-18'],
    fr: ['FR3'] }),
  S('PR-18', 'Home Profile & quiz · 5 Preferences', 'human', '/quiz?step=5', {
    purpose: 'Step 5 of 6. A species the human doesn’t accept is a dealbreaker.',
    ui: ['Species accepted', 'Preferred size', 'Preferred age'],
    actions: ['Next → PR-19'],
    fr: ['FR3'] }),
  S('PR-19', 'Home Profile & quiz · 6 Review', 'human', '/quiz?step=6', {
    purpose: 'Step 6 of 6. Review before saving.',
    ui: ['Answer summary', 'Scoring weights', 'Save Home Profile'],
    actions: ['Save → PR-20'],
    fr: ['FR3'] }),
  S('PR-20', 'Home Profile saved', 'human', '/quiz?done=1', { kind: 'State',
    purpose: 'Confirms the save and offers the Open to Adopt switch.',
    ui: ['Matches recalculated message', 'Open to Adopt toggle', 'See Pets for You'],
    actions: ['See Pets for You → MT-01'],
    rules: ['Match scores update whenever a quiz or résumé changes.'],
    fr: ['FR3', 'FR4'] }),

  /* ---------- 3 Discovery & Search ---------- */
  S('DS-01', 'Browse pets', 'human', '/browse', {
    purpose: 'Search and filter every pet that’s looking for a home.',
    ui: ['Filters: location, species, age, size, temperament, good with', 'Search box and sort', 'Active filter chips', 'Result cards with match %', 'Pagination'],
    actions: ['View → DS-05 Pet résumé'],
    rules: ['Adopted pets never appear.'],
    fr: ['FR6'] }),
  S('DS-02', 'Browse homes', 'pet', '/browse', {
    purpose: 'Search the Home Profiles of humans who are Open to Adopt.',
    ui: ['Filters: location, home type, outdoor space, other pets, kids, activity', 'Home cards (city and household summary only)', 'Pagination'],
    actions: ['View → DS-07 Home Profile'],
    rules: ['No exact address or phone number (NFR4).'],
    fr: ['FR22'] }),
  S('DS-03', 'Search results', 'human', '/search?q=quezon%20city', {
    purpose: 'Results for the top-bar search across pets, homes and posts.',
    ui: ['Result-type filter with counts', 'Pets, Homes and Posts sections', 'Quick action per result'],
    actions: ['Click a result → its profile or post'],
    fr: ['FR6', 'FR22'] }),
  S('DS-04', 'Search · no results', 'human', '/search?q=zebra', { kind: 'Empty state',
    purpose: 'Helps the user recover from an empty search.',
    ui: ['Empty-state message with tips', 'Browse all / See your matches'],
    fr: ['FR6'] }),
  S('DS-05', 'Pet résumé (human view)', 'human', '/pet/mochi', {
    purpose: 'The full résumé as an adopter sees it, with the match explained.',
    ui: ['Invite to Apply, Bookmark, Report', 'Your match card with reasons', 'All résumé sections'],
    actions: ['Invite to Apply → RQ-01', 'Bookmark → BM-03 toast', 'See full breakdown → MT-03', 'Report → RP-01'],
    fr: ['FR7', 'FR8', 'FR9'] }),
  S('DS-06', 'Photo viewer', 'human', '/pet/mochi?modal=photo', { kind: 'Dialog',
    purpose: 'Full-size photos from a résumé.',
    ui: ['Dark overlay', 'Large photo with previous / next', 'Thumbnail strip', 'Close'],
    fr: ['FR7'] }),
  S('DS-07', 'Home Profile (pet view)', 'pet', '/home/cruz', {
    purpose: 'A human’s Home Profile as a pet reads it — like a job posting.',
    ui: ['Apply for this home, Bookmark, Report', 'Your match card', 'Household, lifestyle, what they’re looking for'],
    actions: ['Apply → RQ-03', 'Bookmark → toast', 'Report → RP-01'],
    rules: ['With an open request, Apply becomes “View my request”.', 'City and household summary only (NFR4).'],
    fr: ['FR22', 'FR23', 'FR24'] }),
  S('DS-08', 'Alumni profile (public view)', 'pet', '/pet/luna', {
    purpose: 'An adopted pet’s profile as anyone else sees it.',
    ui: ['Hired badge', '“Hired by …” banner linked to the Furparent', 'No Invite or Apply actions'],
    rules: ['Alumni don’t appear in search or matches.'],
    fr: ['FR28'] }),

  /* ---------- 4 Matching & Suggestions ---------- */
  S('MT-01', 'Pets for You', 'human', '/matches', {
    purpose: 'Ranked suggestions for the human, each with its score explained.',
    ui: ['Open to Adopt toggle', 'Quick filters and sort', 'Match cards: %, meter, top 2 reasons', '“Why this match?” link', 'View résumé / Bookmark'],
    actions: ['Why this match? → MT-03', 'View résumé → DS-05'],
    rules: ['Dealbreakers are removed first; then sorted by score, then newest.'],
    fr: ['FR5'] }),
  S('MT-02', 'Homes for You', 'pet', '/matches', {
    purpose: 'Ranked Open to Adopt homes for the pet.',
    ui: ['Open requests counter (2 of 3)', 'Home match cards', 'View home / Bookmark'],
    actions: ['View home → DS-07', 'Why this match? → breakdown dialog (MT-03)'],
    rules: ['The pet sees the same score as the human (one score, both directions).'],
    fr: ['FR21'] }),
  S('MT-03', 'Match breakdown dialog', 'human', '/matches?modal=why&id=mochi', { kind: 'Dialog',
    purpose: 'Explains a score: the dealbreakers passed, then the 7 weighted criteria.',
    ui: ['Dealbreaker checks', 'Criteria rows with points (20/15/15/15/15/10/10)', 'Total out of 100', 'Top reasons'],
    fr: ['FR5', 'FR21'] }),
  S('MT-04', 'Pets for You · quiz not finished', 'human', '/matches?empty=quiz', { kind: 'Empty state',
    purpose: 'Shown until the human finishes the Home Profile and quiz.',
    ui: ['Setup checklist', 'Take the lifestyle quiz'],
    actions: ['Take the quiz → PR-14'],
    fr: ['FR3', 'FR5'] }),
  S('MT-05', 'Homes for You · résumé in Draft', 'pet', '/matches?empty=draft', { kind: 'Empty state',
    purpose: 'Shown while the pet’s résumé is still a Draft.',
    ui: ['Explanation', 'Continue résumé'],
    actions: ['Continue résumé → PR-07'],
    fr: ['FR20', 'FR21'] }),

  /* ---------- 5 Bookmarks ---------- */
  S('BM-01', 'Bookmarks (human)', 'human', '/bookmarks', {
    purpose: 'Pets the human saved for later.',
    ui: ['Saved pet cards with match', 'View / Remove'],
    actions: ['Remove → “Removed from Bookmarks” toast'],
    fr: ['FR8'] }),
  S('BM-02', 'Bookmarks (pet)', 'pet', '/bookmarks', {
    purpose: 'Homes the pet saved for later.',
    ui: ['Saved home cards', 'View / Remove'],
    actions: ['View → DS-07'],
    fr: ['FR23'] }),
  S('BM-03', 'Saved to Bookmarks (toast)', 'human', '/pet/kulit?saved=1&toast=saved', { kind: 'Toast',
    purpose: 'Feedback after tapping Bookmark on a résumé.',
    ui: ['Button changes to “Bookmarked ✓”', 'Toast bottom-left'],
    fr: ['FR8'] }),
  S('BM-04', 'Bookmarks · empty', 'pet', '/bookmarks?empty=1', { kind: 'Empty state',
    purpose: 'First-time state with a way to find homes.',
    ui: ['Empty message', 'See Homes for You'],
    fr: ['FR23'] }),

  /* ---------- 6 Adoption Requests ---------- */
  S('RQ-01', 'Invite to Apply dialog', 'human', '/pet/mochi?modal=invite', { kind: 'Dialog',
    purpose: 'The human nudges a pet to apply, like a recruiter reaching out.',
    ui: ['Pet summary with match', 'Personal note (optional)', 'Privacy note', 'Send invite'],
    actions: ['Send → toast; the pet gets an invite (RQ-02) and a notification'],
    fr: ['FR9'] }),
  S('RQ-02', 'Invites to Apply', 'pet', '/invites', {
    purpose: 'Invites the pet received. Applying is always the pet’s choice.',
    ui: ['Invite cards: home, match, note', 'View home / Apply / Dismiss', 'Apply disabled during a 30-day cooldown'],
    actions: ['Apply → RQ-03, addressed to that home', 'Dismiss → toast'],
    rules: ['An invite doesn’t count toward the 3-request limit.'],
    fr: ['FR9', 'FR24'] }),
  S('RQ-03', 'Send adoption request', 'pet', '/apply/cruz', {
    purpose: 'The pet’s job application: a cover letter plus the résumé.',
    ui: ['Recipient card with match', 'Cover letter: “Why I’d fit your home”', 'Caretaker’s notes', 'Auto-attached résumé and health summary', 'Send request'],
    actions: ['Send → RQ-04'],
    rules: ['Max 3 open requests; one request per pet + home.'],
    fr: ['FR24'] }),
  S('RQ-04', 'Request sent', 'pet', '/apply/cruz?sent=1', { kind: 'State',
    purpose: 'Confirms the request and its 14-day window.',
    ui: ['Sent badge', 'Open request count', 'Expiry date', 'Track my requests'],
    actions: ['Track my requests → RQ-07'],
    fr: ['FR24'] }),
  S('RQ-05', 'Request limit reached', 'pet', '/home/cruz?modal=limit', { kind: 'Dialog',
    purpose: 'Blocks a 4th open request.',
    ui: ['Explanation', 'The 3 open requests', 'Manage my requests'],
    rules: ['A pet can have up to 3 open requests (Section 5.5).'],
    fr: ['FR24'] }),
  S('RQ-06', 'Cooldown after a decline', 'pet', '/home/garcia?modal=cooldown', { kind: 'Dialog',
    purpose: 'Explains the 30-day wait before applying to the same home again.',
    ui: ['Last request dates', 'Cooldown end date', 'See other homes'],
    fr: ['FR24'] }),
  S('RQ-07', 'My requests · Active', 'pet', '/requests', {
    purpose: 'The pet tracks every request it sent.',
    ui: ['Open / in-process counter', 'Tabs with counts: Active, Closed', 'Rows: home, status, dates', 'Find homes'],
    actions: ['Open → request detail (RQ-14, RQ-15, MG-08)'],
    fr: ['FR24'] }),
  S('RQ-08', 'My requests · Closed', 'pet', '/requests?tab=Closed', {
    purpose: 'Finished requests: declined, withdrawn, expired or adopted.',
    ui: ['Closed tab', 'Final status badges'],
    fr: ['FR24', 'FR30'] }),
  S('RQ-09', 'Requests inbox · New', 'human', '/requests', {
    purpose: 'Requests that pets sent to the human.',
    ui: ['Tabs with counts: New, In progress, Closed', 'New badge and expiry', 'Review button', 'Manage availability'],
    actions: ['Review → RQ-11'],
    rules: ['Requests arrive only while Open to Adopt is on.'],
    fr: ['FR10'] }),
  S('RQ-10', 'Requests inbox · In progress', 'human', '/requests?tab=In%20progress', {
    purpose: 'Approved requests moving toward a decision.',
    ui: ['“Decision needed” badge', 'Meet Scheduled rows'],
    actions: ['Review → MG-11'],
    fr: ['FR10', 'FR12'] }),
  S('RQ-11', 'New request (human)', 'human', '/requests/r4', {
    purpose: 'A new request with the pet’s cover letter and résumé.',
    ui: ['Status stepper', 'Cover letter, caretaker notes', 'Attached résumé, health summary, match', 'Locked thread (opens after approval)', 'Approve / Decline'],
    actions: ['Approve → RQ-12', 'Decline → RQ-13'],
    rules: ['Expires 14 days after it was sent.'],
    fr: ['FR10'] }),
  S('RQ-12', 'Approve request dialog', 'human', '/requests/r4?modal=approve', { kind: 'Dialog',
    purpose: 'Confirms the approval and its effects.',
    ui: ['What happens list', 'Optional message', 'Approve request'],
    actions: ['Approve → Approved; pet In Process; thread opens'],
    rules: ['The pet’s other open requests go On Hold.'],
    fr: ['FR10'] }),
  S('RQ-13', 'Decline request dialog', 'human', '/requests/r4?modal=decline', { kind: 'Dialog',
    purpose: 'Declines with an optional reason and message.',
    ui: ['Reason (optional)', 'Message (optional)', 'Cooldown note'],
    actions: ['Decline → Declined; pet notified'],
    fr: ['FR10'] }),
  S('RQ-14', 'Request · Sent (pet)', 'pet', '/requests/r2?status=Sent', {
    purpose: 'What the pet sees while waiting.',
    ui: ['Stepper at Sent', 'Expiry date', 'Withdraw request'],
    actions: ['Withdraw → RQ-16'],
    fr: ['FR24', 'FR25'] }),
  S('RQ-15', 'Request · On Hold (pet)', 'pet', '/requests/r2', {
    purpose: 'Paused because another of the pet’s requests is in process.',
    ui: ['On Hold badge', 'What happens next'],
    rules: ['Goes back to Sent, with a fresh 14-day clock, if the other request ends without an adoption.'],
    fr: ['FR24'] }),
  S('RQ-16', 'Withdraw request dialog', 'pet', '/requests/r2?modal=withdraw', { kind: 'Dialog',
    purpose: 'The pet can withdraw at any time before the final decision.',
    ui: ['What happens', 'Reason (optional)', 'Keep request / Withdraw'],
    actions: ['Withdraw → Withdrawn; human notified'],
    fr: ['FR25'] }),
  S('RQ-17', 'Request · Declined (pet)', 'pet', '/requests/r3', {
    purpose: 'A closed request with the cooldown explained.',
    ui: ['Declined badge', 'Cooldown date', 'Find other homes'],
    fr: ['FR24'] }),
  S('RQ-18', 'Admin · Requests monitor', 'admin', '/admin/monitor', {
    purpose: 'Every adoption request on the platform.',
    ui: ['Tabs: All requests, Meet & Greets, Overdue', 'Status filter', 'Table with View'],
    actions: ['View → RQ-19'],
    fr: ['FR36'] }),
  S('RQ-19', 'Admin · Request detail', 'admin', '/admin/requests/r5', {
    purpose: 'A read-only record of one request.',
    ui: ['Timeline of status changes', 'Cover letter', 'Parties with account links', 'Meet & Greet info', 'Send reminder / Resolve issue'],
    actions: ['Resolve issue → AL-07'],
    rules: ['Thread messages stay private unless attached to a report.'],
    fr: ['FR36', 'FR37'] }),

  /* ---------- 7 Meet & Greet ---------- */
  S('MG-01', 'Meet & Greet availability', 'human', '/availability', {
    purpose: 'The human’s bookable slots.',
    ui: ['+ Add slot', 'Upcoming slots (open / booked)', 'Past Meet & Greets', 'Privacy note'],
    actions: ['+ Add slot → MG-02', 'View request (booked slot) → MG-07'],
    fr: ['FR11'] }),
  S('MG-02', 'Add slot dialog', 'human', '/availability?modal=slot', { kind: 'Dialog',
    purpose: 'Creates a slot: date, time and meeting place.',
    ui: ['Date and time', 'Meeting place type', 'Place details', 'Repeat'],
    actions: ['Add slot → toast'],
    fr: ['FR11'] }),
  S('MG-03', 'Book a slot (pet)', 'pet', '/requests/r1?status=Approved', {
    purpose: 'After approval, the pet books one of the human’s slots.',
    ui: ['Stepper at Approved', 'Open slots as radio cards', 'Book this slot', 'Request thread now open'],
    actions: ['Book → MG-04'],
    rules: ['Reminder after 7 days without booking; the request expires after 14.'],
    fr: ['FR26'] }),
  S('MG-04', 'Slot booked · awaiting confirmation (pet)', 'pet', '/requests/r1?status=Slot%20Booked', {
    purpose: 'Waiting for the human to confirm.',
    ui: ['Booked slot summary', 'Change slot', 'Withdraw'],
    fr: ['FR26'] }),
  S('MG-05', 'Confirm booking (human)', 'human', '/requests/r1?status=Slot%20Booked', {
    purpose: 'The human confirms the booking or offers another time.',
    ui: ['Booked slot', 'Confirm / Propose another time'],
    actions: ['Confirm → MG-07', 'Propose → MG-06'],
    fr: ['FR11'] }),
  S('MG-06', 'Propose another time dialog', 'human', '/requests/r1?status=Slot%20Booked&modal=propose', { kind: 'Dialog',
    purpose: 'Offers the pet a different slot.',
    ui: ['Open slots', '+ Add a new slot', 'Message'],
    actions: ['Send → request back to Approved; the pet rebooks'],
    fr: ['FR11'] }),
  S('MG-07', 'Meet Scheduled (human)', 'human', '/requests/r1', {
    purpose: 'The confirmed meeting, with contact details unlocked.',
    ui: ['Meet & Greet card: date, place, contact, exact address', 'Reschedule / Cancel meeting', 'Request thread'],
    actions: ['Reschedule → MG-06', 'Cancel → MG-10'],
    rules: ['Phones and addresses are shared only after confirmation (NFR4).', 'Reminders 1 day and 1 hour before.'],
    fr: ['FR11'] }),
  S('MG-08', 'Meet Scheduled (pet)', 'pet', '/requests/r1', {
    purpose: 'The pet’s view of the confirmed meeting.',
    ui: ['Meet & Greet card', 'Reschedule / Cancel / Withdraw'],
    actions: ['Reschedule → MG-09', 'Cancel → MG-10'],
    fr: ['FR26'] }),
  S('MG-09', 'Reschedule dialog (pet)', 'pet', '/requests/r1?modal=reschedule', { kind: 'Dialog',
    purpose: 'The pet asks for a different slot.',
    ui: ['Current slot', 'Open slots', 'Reason'],
    actions: ['Request → the human confirms again (MG-05)'],
    fr: ['FR26'] }),
  S('MG-10', 'Cancel meeting dialog', 'human', '/requests/r1?modal=cancel', { kind: 'Dialog',
    purpose: 'Either side can cancel, with a required reason.',
    ui: ['Reason (required)', 'Details', 'Keep meeting / Cancel meeting'],
    actions: ['Cancel → request back to Approved; booking reopens'],
    fr: ['FR11', 'FR26'] }),
  S('MG-11', 'Decision needed (human)', 'human', '/requests/r5', {
    purpose: 'After the meeting time passes, the human decides.',
    ui: ['Stepper at Awaiting Decision', 'Adopt / Decline / It didn’t happen', 'Reminder note'],
    actions: ['Adopt → AL-01', 'Decline → MG-14', 'It didn’t happen → MG-13'],
    rules: ['Adopt and Decline are available only after the meeting time (NFR3).'],
    fr: ['FR12'] }),
  S('MG-12', 'Awaiting decision (pet)', 'pet', '/requests/r1?status=Awaiting%20Decision', {
    purpose: 'The pet waits for the human’s decision.',
    ui: ['Explanation', 'Withdraw is still available'],
    fr: ['FR25'] }),
  S('MG-13', '“It didn’t happen” dialog', 'human', '/requests/r5?modal=didnt', { kind: 'Dialog',
    purpose: 'Reports a missed meeting and reopens booking.',
    ui: ['What happened', 'Details'],
    actions: ['Reopen booking → request back to Approved'],
    fr: ['FR12'] }),
  S('MG-14', 'Decline after the meeting', 'human', '/requests/r5?modal=notadopted', { kind: 'Dialog',
    purpose: 'Ends the request as Not Adopted.',
    ui: ['Message to the caretaker (optional)', 'Cooldown note'],
    actions: ['Decline → Not Adopted; the pet goes back to Looking for a Home'],
    fr: ['FR12'] }),
  S('MG-15', 'Admin · Meet & Greets', 'admin', '/admin/monitor?tab=Meet%20%26%20Greets', {
    purpose: 'All scheduled and past meetings.',
    ui: ['Meet & Greets tab', 'Date, time and place per request'],
    fr: ['FR36'] }),
  S('MG-16', 'Admin · Overdue decisions', 'admin', '/admin/monitor?tab=Overdue', {
    purpose: 'Requests with no decision 7 days after the meeting.',
    ui: ['Overdue badge', 'View / Resolve'],
    actions: ['Resolve → AL-07'],
    fr: ['FR36'] }),

  /* ---------- 8 Adoption & Alumni ---------- */
  S('AL-01', 'Adopt confirmation dialog', 'human', '/requests/r5?modal=adopt', { kind: 'Dialog',
    purpose: 'The final, permanent decision.',
    ui: ['Pet → you illustration', 'What happens list', 'Confirmation checkbox', 'Yes, adopt'],
    actions: ['Adopt → AL-02'],
    rules: ['Nobody sets “Adopted” by hand — the system does it on this action.'],
    fr: ['FR12', 'FR13', 'FR28'] }),
  S('AL-02', 'You’re a Furparent', 'human', '/requests/r5?status=Adopted&modal=furparent', { kind: 'Dialog',
    purpose: 'Celebrates the adoption on the human’s side.',
    ui: ['Hired badge between the two profiles', 'View alumni profile', 'Share your adoption story'],
    actions: ['Share your adoption story → FD-04'],
    fr: ['FR13', 'FR14'] }),
  S('AL-03', 'You got Hired', 'pet', '/requests/r1?status=Adopted&modal=hired', { kind: 'Dialog',
    purpose: 'Celebrates the adoption on the pet’s side.',
    ui: ['Hired badge', 'View my alumni profile', 'Post an update'],
    fr: ['FR28', 'FR29'] }),
  S('AL-04', 'Adopted request record', 'human', '/requests/r0', {
    purpose: 'The completed request, kept as the adoption record.',
    ui: ['Completed stepper', 'Full thread history', 'View alumni profile'],
    fr: ['FR14'] }),
  S('AL-05', 'Alumni profile (Furparent view)', 'human', '/pet/luna', {
    purpose: 'The Furparent’s view of their adopted pet.',
    ui: ['“Hired by …” banner', 'Adoption details', 'Write an adoption story'],
    actions: ['Adoption details → AL-06', 'Write an adoption story → FD-04'],
    fr: ['FR13', 'FR14', 'FR28'] }),
  S('AL-06', 'Adoption details dialog', 'human', '/pet/luna?modal=adoption', { kind: 'Dialog',
    purpose: 'Timeline and facts of the adoption.',
    ui: ['Pet ↔ Furparent link', 'Timeline', 'Days to adoption, cover letter', 'Open request record'],
    fr: ['FR14'] }),
  S('AL-07', 'Admin · Resolve adoption issue', 'admin', '/admin/resolve', {
    purpose: 'Fixes problems such as a returned pet. The only manual status change in the system.',
    ui: ['Pet and related request', 'Action options', 'Reason (required)', 'Recent resolutions'],
    actions: ['Review change → AL-08'],
    fr: ['FR37'] }),
  S('AL-08', 'Admin · Confirm status change', 'admin', '/admin/resolve?modal=confirm', { kind: 'Dialog',
    purpose: 'Shows exactly what will change before applying it.',
    ui: ['Before → after status', 'Furparent link change', 'Reason'],
    actions: ['Apply → toast; both accounts notified; logged'],
    rules: ['Every override is logged with who, when and why (NFR9).'],
    fr: ['FR37'] }),
  S('AL-09', 'Admin · Alumni profiles', 'admin', '/admin/accounts?tab=Alumni', {
    purpose: 'Monitors adopted pets and their Furparents.',
    ui: ['Alumni tab', 'Furparent and adoption date', 'View / Resolve issue'],
    fr: ['FR38'] }),

  /* ---------- 9 Notifications ---------- */
  S('NT-01', 'Alerts dropdown', 'human', '/feed?menu=alerts', { kind: 'Dropdown',
    purpose: 'A quick look at the latest notifications from any page.',
    ui: ['Latest 4 notifications with unread dots', 'Mark all as read', 'See all notifications'],
    actions: ['See all → NT-02'],
    fr: ['FR15'] }),
  S('NT-02', 'Notifications (human)', 'human', '/notifications', {
    purpose: 'All of the human’s notifications.',
    ui: ['Tabs: All, Requests, Meet & Greets, Account', 'Unread rows highlighted', 'Mark all as read, Settings'],
    rules: ['In-app only; email and SMS are future scope.'],
    fr: ['FR15'] }),
  S('NT-03', 'Notifications (pet)', 'pet', '/notifications', {
    purpose: 'All of the pet’s notifications.',
    ui: ['Invites, request updates, Meet & Greet reminders, account messages'],
    fr: ['FR31'] }),
  S('NT-04', 'Admin · Announcements', 'admin', '/admin/announcements', {
    purpose: 'Platform-wide messages.',
    ui: ['Title, message, audience, publish time', 'Past announcements'],
    actions: ['Publish… → NT-05'],
    fr: ['FR39'] }),
  S('NT-05', 'Publish announcement dialog', 'admin', '/admin/announcements?modal=publish', { kind: 'Dialog',
    purpose: 'Preview and confirm before sending.',
    ui: ['Preview card', 'Audience and delivery'],
    actions: ['Publish now → toast; recipients notified'],
    fr: ['FR39'] }),

  /* ---------- 10 Community Feed & Stories ---------- */
  S('FD-01', 'Community feed (human)', 'human', '/feed', {
    purpose: 'A social feed shared by everyone, like Facebook or Instagram.',
    ui: ['Mini profile card', 'Composer: Start a post, Photo, Write an adoption story', 'Shuffled posts: For Hire, Hired, Update, Story', 'Pets for You and announcement cards'],
    actions: ['Start a post → FD-03', 'Write an adoption story → FD-04', '••• → FD-06 options'],
    rules: ['The feed is separate from the ranked matches.'],
    fr: ['FR17', 'FR14'] }),
  S('FD-02', 'Community feed (pet)', 'pet', '/feed', {
    purpose: 'The same feed from the pet’s side.',
    ui: ['Pet mini profile with status', 'Share an update', 'Homes for You and Invites cards'],
    actions: ['Share an update → FD-03'],
    fr: ['FR29'] }),
  S('FD-03', 'Create post dialog', 'pet', '/feed?modal=post', { kind: 'Dialog',
    purpose: 'Write a text or photo post.',
    ui: ['Author and post type', 'Text', 'Photos'],
    actions: ['Post → toast; it appears in the feed'],
    fr: ['FR17', 'FR29'] }),
  S('FD-04', 'Write an adoption story', 'human', '/feed?modal=story', { kind: 'Dialog',
    purpose: 'Furparents tell how their pet got Hired.',
    ui: ['Adopted pet picker', 'Title', 'Story', 'Photos'],
    fr: ['FR14'] }),
  S('FD-05', 'Post detail & comments', 'human', '/post/p2', {
    purpose: 'One post with all its comments.',
    ui: ['Post with reactions', 'Comment box', 'Comments with Like / Reply / Report', 'Author card and more posts'],
    fr: ['FR17'] }),
  S('FD-06', 'Post options menu', 'human', '/post/p5?menu=post', { kind: 'Dropdown',
    purpose: 'Actions on a post. Own posts: Edit, Delete. Others’ posts: Save, Report.',
    ui: ['••• menu'],
    actions: ['Delete post → FD-07', 'Report post → report dialog (RP-01)'],
    fr: ['FR17'] }),
  S('FD-07', 'Delete post dialog', 'human', '/post/p5?modal=delete', { kind: 'Dialog',
    purpose: 'Confirms deleting one’s own post.',
    ui: ['What gets removed', 'Cancel / Delete post'],
    fr: ['FR17'] }),

  /* ---------- 11 Reports & Moderation ---------- */
  S('RP-01', 'Report dialog', 'pet', '/home/reyes?modal=report', { kind: 'Dialog',
    purpose: 'Report a profile, post, comment or account.',
    ui: ['Reason options', 'Details', 'Submit report'],
    actions: ['Submit → RP-02'],
    fr: ['FR16', 'FR32'] }),
  S('RP-02', 'Report sent (toast)', 'pet', '/home/reyes?toast=report', { kind: 'Toast',
    purpose: 'Confirms the report was received.',
    ui: ['Toast bottom-left'],
    fr: ['FR16', 'FR32'] }),
  S('RP-03', 'Admin · Reports queue', 'admin', '/admin/reports', {
    purpose: 'Open reports, most reported first.',
    ui: ['Tabs: Open, Resolved', 'Reported item, reason, count, date', 'Review'],
    actions: ['Review → RP-04'],
    fr: ['FR35'] }),
  S('RP-04', 'Admin · Review report', 'admin', '/admin/reports/rep1', {
    purpose: 'See the content, the reports and the account before acting.',
    ui: ['Reported content preview', 'List of reports', 'Reported account summary', 'Choose action… / Dismiss'],
    actions: ['Choose action… → RP-05'],
    fr: ['FR35'] }),
  S('RP-05', 'Admin · Take action dialog', 'admin', '/admin/reports/rep1?modal=action', { kind: 'Dialog',
    purpose: 'Remove, suspend or dismiss — always with a reason.',
    ui: ['Action options', 'Reason shown to the owner', 'Notify reporters'],
    actions: ['Apply → owner and reporters notified; logged'],
    rules: ['Removed content can be restored from Resolved.'],
    fr: ['FR35', 'FR34'] }),

  /* ---------- 12 Account Administration ---------- */
  S('AC-01', 'Settings (pet)', 'pet', '/settings', {
    purpose: 'Account settings for the pet account.',
    ui: ['Verified details (locked) + Request a change', 'Caretaker contact', 'Notification preferences', 'Sign-in & security', 'Deactivate account'],
    actions: ['Request a change → AC-03'],
    rules: ['After adoption the pet keeps its account; the caretaker contact is updated.'] }),
  S('AC-02', 'Settings (human)', 'human', '/settings', {
    purpose: 'Account settings for the human.',
    ui: ['Verified details', 'Private contact details', 'Notification preferences', 'Change password', 'Deactivate'],
    actions: ['Change password → AC-04', 'Deactivate → AC-05'] }),
  S('AC-03', 'Request a change dialog', 'pet', '/settings?modal=change', { kind: 'Dialog',
    purpose: 'Asks an admin to change a locked, verified field.',
    ui: ['Field', 'New value', 'Reason', 'Supporting document'] }),
  S('AC-04', 'Change password dialog', 'human', '/settings?modal=password', { kind: 'Dialog',
    purpose: 'Changes the password; other devices are signed out.',
    ui: ['Current / new / confirm password'] }),
  S('AC-05', 'Deactivate account dialog', 'human', '/settings?modal=deactivate', { kind: 'Dialog',
    purpose: 'The owner closes their own account.',
    ui: ['What happens', 'Reason', 'Password confirmation'],
    rules: ['Records are kept for adoption history and logs.'] }),
  S('AC-06', 'Admin · Accounts', 'admin', '/admin/accounts', {
    purpose: 'All Pet and Human accounts.',
    ui: ['Tabs: All, Pet, Human, Alumni', 'Search and status filter', 'Status badges', 'View'],
    actions: ['View → AC-07'],
    fr: ['FR34'] }),
  S('AC-07', 'Admin · Account detail', 'admin', '/admin/accounts/mochi', {
    purpose: 'Everything about one account, and the actions on it.',
    ui: ['Header with status and actions', 'Status history', 'Requests', 'Verification documents', 'Reports and recent activity'],
    actions: ['Suspend → AC-08', 'Deactivate → AC-10'],
    fr: ['FR34'] }),
  S('AC-08', 'Admin · Suspend account dialog', 'admin', '/admin/accounts/mochi?modal=suspend', { kind: 'Dialog',
    purpose: 'Hides the profile; the owner sees the reason on AU-21.',
    ui: ['Reason (required)', 'What happens'],
    fr: ['FR34'] }),
  S('AC-09', 'Admin · Reactivate account dialog', 'admin', '/admin/accounts/maxdealer?modal=reactivate', { kind: 'Dialog',
    purpose: 'Restores a suspended account.',
    ui: ['Suspension record', 'Log note (required)'],
    fr: ['FR34'] }),
  S('AC-10', 'Admin · Deactivate account dialog', 'admin', '/admin/accounts/mochi?modal=deactivate', { kind: 'Dialog',
    purpose: 'Removes an account while keeping its records.',
    ui: ['Reason (required)', 'Confirmation checkbox'],
    fr: ['FR34'] }),

  /* ---------- 13 Analytics ---------- */
  S('AN-01', 'My stats (pet)', 'pet', '/stats', {
    purpose: 'How the pet’s résumé is doing.',
    ui: ['Tiles: views, bookmarks, requests, invites', 'Views chart and where views come from', 'Request history'],
    fr: ['FR30'] }),
  S('AN-02', 'Match & request history (human)', 'human', '/stats', {
    purpose: 'The human’s match results and request history.',
    ui: ['Tiles: matches, bookmarks, requests, adopted', 'Match scores and request outcomes charts', 'Request history'],
    fr: ['FR5', 'FR10'] }),
  S('AN-03', 'Admin · Platform dashboard', 'admin', '/admin', {
    purpose: 'Platform analytics at a glance.',
    ui: ['Tiles: accounts, queue, pets by status, requests, Meet & Greets, adoptions, average days to adoption', 'Charts', 'Needs attention list'],
    fr: ['FR40'] }),

  /* ---------- 14 Activity Logs ---------- */
  S('LG-01', 'My activity (pet)', 'pet', '/activity', {
    purpose: 'The pet account’s own important actions, including system status changes.',
    ui: ['Type tabs', 'When / activity / type table', 'Download CSV'],
    fr: ['FR41'] }),
  S('LG-02', 'My activity (human)', 'human', '/activity', {
    purpose: 'The human’s own important actions, including sign-ins.',
    ui: ['Type tabs', 'Activity table'],
    fr: ['FR41'] }),
  S('LG-03', 'Admin · Activity logs', 'admin', '/admin/logs', {
    purpose: 'Every admin action and status change on the platform.',
    ui: ['Actor and type filters', 'Export CSV', 'Rows: when, who, what, type, why'],
    actions: ['Click a row → LG-04'],
    fr: ['FR41'] }),
  S('LG-04', 'Admin · Log entry detail', 'admin', '/admin/logs?modal=log&i=4', { kind: 'Drawer',
    purpose: 'Full detail of one log entry.',
    ui: ['Actor, action, target', 'Before → after', 'Reason', 'Read-only note'],
    rules: ['Log entries can’t be edited or deleted (NFR9).'],
    fr: ['FR41'] }),
]

// Module user flows: each row is a chain of [screen id, label, arrow label, kind].
// kind: screen (default) · dialog · system · end
export const FLOWS = {
  auth: [
    { lane: 'Visitor', steps: [['AU-01', 'Landing page'], ['AU-07', 'Choose account type', 'Join now'], ['AU-08–17', 'Sign-up wizard · 5 steps'], ['AU-18', 'Pending approval', 'Submit', 'system']] },
    { lane: 'Admin', steps: [['AU-22', 'Verification queue'], ['AU-23 / 24', 'Review account', 'Review'], ['AU-26', 'Approved → Active', 'Approve', 'system'], ['FD-01 / 02', 'Owner gets full access', '', 'end']] },
    { lane: 'If denied', steps: [['AU-25', 'Deny with reason', '', 'dialog'], ['AU-20', 'Owner sees reason', 'Deny'], ['AU-19', 'Edit details', 'Correct'], ['AU-18', 'Back to Pending', 'Resubmit', 'system']] },
    { lane: 'Returning user', steps: [['AU-02', 'Sign in'], ['AU-03', 'Error state', 'Wrong password'], ['AU-04', 'Forgot password', 'Forgot?'], ['AU-05', 'Link sent', 'Send'], ['AU-06', 'New password', 'Open link']] },
    { lane: 'Blocked', steps: [['AU-02', 'Sign in'], ['AU-18 / 20 / 21', 'Status screen only', 'Not Active', 'end']] },
  ],
  profile: [
    { lane: 'Pet', steps: [['AU-26', 'Account approved', '', 'system'], ['PR-02', 'Résumé in Draft'], ['PR-03–08', 'Edit résumé · 6 steps', 'Continue'], ['PR-10', 'Looking for a Home', 'Publish', 'system'], ['PR-01', 'My résumé']] },
    { lane: 'Pet · photos', steps: [['PR-04', 'Photos step'], ['PR-09', 'Add photo', '+ Add photo', 'dialog'], ['PR-04', 'Photo added', 'Add', 'system']] },
    { lane: 'Human', steps: [['AU-26', 'Account approved', '', 'system'], ['PR-14–19', 'Home Profile & quiz · 6 steps'], ['PR-20', 'Saved · Open to Adopt', 'Save', 'system'], ['PR-11', 'My Home Profile']] },
    { lane: 'Human · edits', steps: [['PR-11', 'My Home Profile'], ['PR-12', 'Edit intro', 'Edit intro', 'dialog'], ['PR-11', 'Profile updated', 'Save', 'system']] },
    { lane: 'Human · pause', steps: [['PR-11', 'My Home Profile'], ['PR-13', 'Turn off Open to Adopt', 'Toggle off', 'dialog'], ['', 'No new requests; open ones continue', 'Turn off', 'system']] },
  ],
  discovery: [
    { lane: 'Human · browse', steps: [['DS-01', 'Browse pets + filters'], ['DS-05', 'Pet résumé', 'View'], ['DS-06', 'Photo viewer', 'Photo', 'dialog']] },
    { lane: 'Human · search', steps: [['GN-01', 'Top-bar search'], ['DS-03', 'Search results', 'Enter'], ['DS-05', 'Pet résumé', 'Open'], ['RQ-01', 'Invite to Apply', 'Invite', 'dialog']] },
    { lane: 'No results', steps: [['DS-03', 'Search'], ['DS-04', 'No results', 'Nothing found'], ['DS-01', 'Browse all', 'Browse all']] },
    { lane: 'Pet', steps: [['DS-02', 'Browse homes + filters'], ['DS-07', 'Home Profile', 'View'], ['RQ-03', 'Send request', 'Apply']] },
    { lane: 'Anyone', steps: [['FD-01', 'Post by an alum'], ['DS-08', 'Alumni profile (read-only)', 'Open profile', 'end']] },
  ],
  matching: [
    { lane: 'Human', steps: [['PR-19', 'Finish the quiz'], ['MT-01', 'Pets for You', 'Save'], ['MT-03', 'Match breakdown', 'Why this match?', 'dialog'], ['DS-05', 'Pet résumé', 'View résumé']] },
    { lane: 'Human · not set up', steps: [['MT-04', 'Quiz not finished'], ['PR-14', 'Lifestyle quiz', 'Take the quiz'], ['MT-01', 'Pets for You', 'Save']] },
    { lane: 'Pet', steps: [['PR-08', 'Publish résumé'], ['MT-02', 'Homes for You', 'Publish'], ['DS-07', 'Home Profile', 'View home'], ['RQ-03', 'Send request', 'Apply']] },
    { lane: 'Pet · Draft', steps: [['MT-05', 'Résumé in Draft'], ['PR-07', 'Continue résumé', 'Continue'], ['MT-02', 'Homes for You', 'Publish']] },
    { lane: 'System', steps: [['', 'Quiz or résumé changes', '', 'system'], ['', 'Dealbreakers removed', '', 'system'], ['', 'Weighted score 0–100', '', 'system'], ['MT-01 / 02', 'Lists re-ranked', '', 'end']] },
  ],
  bookmarks: [
    { lane: 'Human', steps: [['DS-05', 'Pet résumé'], ['BM-03', 'Saved toast', 'Bookmark', 'system'], ['BM-01', 'Bookmarks', 'Me → Bookmarks'], ['DS-05', 'Pet résumé', 'View']] },
    { lane: 'Pet', steps: [['DS-07', 'Home Profile'], ['BM-02', 'Bookmarks', 'Bookmark'], ['RQ-03', 'Send request', 'Apply']] },
    { lane: 'First time', steps: [['BM-04', 'No bookmarks yet'], ['MT-02', 'Homes for You', 'See Homes for You']] },
  ],
  requests: [
    { lane: 'Human (optional)', steps: [['DS-05', 'Pet résumé'], ['RQ-01', 'Invite to Apply', 'Invite', 'dialog'], ['RQ-02', 'Pet sees invite', 'Send', 'system']] },
    { lane: 'Pet', steps: [['DS-07 / RQ-02', 'Home or invite'], ['RQ-03', 'Send request', 'Apply'], ['RQ-04', 'Request sent', 'Send'], ['RQ-07', 'My requests', 'Track']] },
    { lane: 'Pet · blocked', steps: [['DS-07', 'Apply'], ['RQ-05', '3 open requests', 'At limit', 'dialog']] },
    { lane: 'Pet · cooldown', steps: [['DS-07', 'Apply'], ['RQ-06', '30-day cooldown', 'Declined < 30 days', 'dialog']] },
    { lane: 'Human', steps: [['RQ-09', 'Inbox · New'], ['RQ-11', 'Review request', 'Review'], ['RQ-12', 'Approve', 'Approve', 'dialog'], ['MG-03', 'Pet books a slot', 'Approved', 'system']] },
    { lane: 'Human · decline', steps: [['RQ-11', 'Review request'], ['RQ-13', 'Decline', 'Decline', 'dialog'], ['RQ-17', 'Pet sees Declined', '', 'system']] },
    { lane: 'Pet · withdraw', steps: [['RQ-14 / 15', 'Sent or On Hold'], ['RQ-16', 'Withdraw', 'Withdraw', 'dialog'], ['RQ-08', 'Closed tab', 'Confirm']] },
    { lane: 'Admin', steps: [['RQ-18', 'Requests monitor'], ['RQ-19', 'Request detail', 'View'], ['AL-07', 'Resolve issue', 'Resolve']] },
  ],
  meet: [
    { lane: 'Human · setup', steps: [['MG-01', 'Availability'], ['MG-02', 'Add slot', '+ Add slot', 'dialog'], ['MG-01', 'Slot open for booking', 'Add', 'system']] },
    { lane: 'Pet', steps: [['MG-03', 'Book a slot'], ['MG-04', 'Awaiting confirmation', 'Book']] },
    { lane: 'Human', steps: [['MG-05', 'Confirm booking'], ['MG-07', 'Meet Scheduled', 'Confirm'], ['', 'Reminders 1 day / 1 hour', '', 'system'], ['MG-11', 'Decision needed', 'Time passes', 'system']] },
    { lane: 'Other time', steps: [['MG-05', 'Confirm booking'], ['MG-06', 'Propose another time', 'Propose', 'dialog'], ['MG-03', 'Pet rebooks', 'Send', 'system']] },
    { lane: 'Pet · reschedule', steps: [['MG-08', 'Meet Scheduled'], ['MG-09', 'Reschedule', 'Reschedule', 'dialog'], ['MG-05', 'Human confirms again', 'Request']] },
    { lane: 'Either · cancel', steps: [['MG-07 / 08', 'Meet Scheduled'], ['MG-10', 'Cancel with reason', 'Cancel', 'dialog'], ['MG-03', 'Booking reopens', 'Confirm', 'system']] },
    { lane: 'Decision', steps: [['MG-11', 'Decision needed'], ['AL-01', 'Adopt', 'Choose', 'dialog'], ['MG-14', 'Decline → Not Adopted', 'or', 'dialog'], ['MG-13', 'It didn’t happen → rebook', 'or', 'dialog']] },
    { lane: 'Admin', steps: [['MG-15', 'Meet & Greets'], ['MG-16', 'Overdue decisions', '7+ days'], ['AL-07', 'Resolve issue', 'Resolve']] },
  ],
  adoption: [
    { lane: 'Human', steps: [['MG-11', 'Decision needed'], ['AL-01', 'Adopt?', 'Adopt', 'dialog'], ['AL-02', 'You’re a Furparent', 'Yes, adopt', 'dialog'], ['AL-05', 'Alumni profile', 'View']] },
    { lane: 'System', steps: [['AL-01', 'Adopt confirmed', '', 'system'], ['', 'Pet → Adopted — Hired', '', 'system'], ['', 'Human → Furparent; profiles linked', '', 'system'], ['', 'Pet’s other requests close', '', 'end']] },
    { lane: 'Pet', steps: [['AL-03', 'You got Hired', '', 'dialog'], ['DS-08', 'Alumni profile', 'View'], ['FD-03', 'Post an update', 'Post', 'dialog']] },
    { lane: 'Furparent', steps: [['AL-05', 'Alumni profile'], ['AL-06', 'Adoption details', 'Details', 'dialog'], ['AL-04', 'Request record', 'Open record'], ['FD-04', 'Adoption story', 'Write story', 'dialog']] },
    { lane: 'Admin', steps: [['AL-09', 'Alumni profiles'], ['AL-07', 'Resolve issue', 'Resolve'], ['AL-08', 'Confirm change', 'Review', 'dialog'], ['LG-03', 'Written to logs', 'Apply', 'system']] },
  ],
  notifications: [
    { lane: 'System', steps: [['', 'Event: request, meeting, verification', '', 'system'], ['NT-01', 'Alerts dropdown', 'Notify'], ['NT-02 / 03', 'Notifications page', 'See all'], ['', 'Related screen', 'Open', 'end']] },
    { lane: 'Admin', steps: [['NT-04', 'Announcements'], ['NT-05', 'Publish?', 'Publish…', 'dialog'], ['NT-01', 'Everyone’s Alerts', 'Publish now', 'system']] },
  ],
  feed: [
    { lane: 'Anyone', steps: [['FD-01 / 02', 'Feed'], ['FD-03', 'Create post', 'Start a post', 'dialog'], ['FD-01', 'Post appears', 'Post', 'system']] },
    { lane: 'Furparent', steps: [['FD-01', 'Feed'], ['FD-04', 'Adoption story', 'Write story', 'dialog'], ['FD-01', 'Story appears', 'Post', 'system']] },
    { lane: 'Engage', steps: [['FD-01', 'Feed'], ['FD-05', 'Post detail', 'Comments'], ['FD-06', 'Options menu', '•••', 'dialog'], ['FD-07', 'Delete post', 'Delete', 'dialog']] },
    { lane: 'System', steps: [['PR-10', 'Résumé published', '', 'system'], ['FD-02', 'Automatic “For Hire” post', '', 'end']] },
  ],
  reports: [
    { lane: 'Pet / Human', steps: [['DS-07 / FD-05', 'Profile, post or comment'], ['RP-01', 'Report dialog', 'Report', 'dialog'], ['RP-02', 'Report sent', 'Submit', 'system']] },
    { lane: 'Admin', steps: [['RP-03', 'Reports queue'], ['RP-04', 'Review report', 'Review'], ['RP-05', 'Take action', 'Choose action…', 'dialog'], ['AU-21', 'Owner sees suspension', 'Suspend', 'system']] },
    { lane: 'Admin · no issue', steps: [['RP-04', 'Review report'], ['RP-03', 'Moved to Resolved', 'Dismiss', 'system']] },
  ],
  accounts: [
    { lane: 'Owner', steps: [['GN-01', 'Me menu'], ['AC-01 / 02', 'Settings', 'Settings'], ['AC-03', 'Request a change', 'Locked field', 'dialog']] },
    { lane: 'Owner · security', steps: [['AC-02', 'Settings'], ['AC-04', 'Change password', 'Change password', 'dialog']] },
    { lane: 'Owner · leave', steps: [['AC-02', 'Settings'], ['AC-05', 'Deactivate', 'Deactivate', 'dialog'], ['AU-01', 'Signed out', 'Confirm', 'end']] },
    { lane: 'Admin', steps: [['AC-06', 'Accounts'], ['AC-07', 'Account detail', 'View'], ['AC-08', 'Suspend', 'Suspend', 'dialog'], ['AC-09', 'Reactivate later', 'Reactivate', 'dialog']] },
    { lane: 'Admin · remove', steps: [['AC-07', 'Account detail'], ['AC-10', 'Deactivate', 'Deactivate', 'dialog'], ['LG-03', 'Written to logs', 'Confirm', 'system']] },
  ],
  analytics: [
    { lane: 'Pet', steps: [['GN-01', 'Me menu'], ['AN-01', 'My stats', 'My stats'], ['RQ-14', 'Request detail', 'Open']] },
    { lane: 'Human', steps: [['GN-01', 'Me menu'], ['AN-02', 'Match & request history', 'History'], ['RQ-11', 'Request detail', 'Open']] },
    { lane: 'Admin', steps: [['AN-03', 'Dashboard'], ['AU-22', 'Verification queue', 'Needs attention'], ['MG-16', 'Overdue decisions', 'Overdue']] },
  ],
  logs: [
    { lane: 'Pet / Human', steps: [['GN-01', 'Me menu'], ['LG-01 / 02', 'My activity', 'My activity']] },
    { lane: 'System', steps: [['', 'Status change or admin action', '', 'system'], ['LG-03', 'New log entry', 'Write', 'system']] },
    { lane: 'Admin', steps: [['LG-03', 'Activity logs'], ['LG-04', 'Log entry detail', 'Click row', 'dialog']] },
  ],
}

export const SITEMAP = [
  { role: 'Visitor', groups: [
    ['Public', ['AU-01 Landing page', 'AU-02 Sign in · AU-03 error', 'AU-04 Forgot password → AU-05 → AU-06']],
    ['Join', ['AU-07 Choose account type', 'AU-08–12 Pet sign-up (5 steps)', 'AU-13–17 Human sign-up (5 steps)']],
    ['Not yet active', ['AU-18 Pending approval', 'AU-19 Edit submitted details', 'AU-20 Denied', 'AU-21 Suspended']],
  ] },
  { role: 'Pet', groups: [
    ['Top navigation', ['FD-02 Home feed', 'MT-02 Homes for You', 'DS-02 Browse homes', 'RQ-07 My requests', 'NT-03 Alerts / notifications', 'GN-01 Me menu']],
    ['Me menu', ['PR-01 My résumé', 'PR-03–08 Edit résumé', 'RQ-02 Invites to Apply', 'BM-02 Bookmarks', 'AN-01 My stats', 'LG-01 My activity', 'AC-01 Settings']],
    ['Reached from content', ['DS-07 Home Profile → RQ-03 Send request', 'MG-03 · MG-08 Request detail', 'DS-03 Search results', 'FD-05 Post detail']],
  ] },
  { role: 'Human', groups: [
    ['Top navigation', ['FD-01 Home feed', 'MT-01 Pets for You', 'DS-01 Browse pets', 'RQ-09 Requests inbox', 'NT-01 Alerts → NT-02', 'Me menu']],
    ['Me menu', ['PR-11 My Home Profile', 'PR-14–19 Home Profile & quiz', 'MG-01 Meet & Greet availability', 'BM-01 Bookmarks', 'AN-02 Match & request history', 'LG-02 My activity', 'AC-02 Settings']],
    ['Reached from content', ['DS-05 Pet résumé', 'RQ-11 · MG-07 · MG-11 Request detail', 'AL-05 Alumni profile', 'FD-05 Post detail']],
  ] },
  { role: 'Admin', groups: [
    ['Sidebar', ['AN-03 Dashboard', 'AU-22 Verification → AU-23 / 24', 'RP-03 Reports → RP-04', 'RQ-18 Requests & Meets → RQ-19', 'AL-07 Resolve Issues', 'AC-06 Accounts & Alumni → AC-07', 'NT-04 Announcements', 'LG-03 Activity Logs → LG-04']],
    ['Admin-only rules', ['Admin accounts are created by the system', 'Every action needs a reason and is logged', 'Can see verification documents']],
  ] },
]

// Section 4 of the proposal, mapped to screens.
export const CORE = [
  ['Pet', 'Signs up and submits verification details. The account shows Pending Verification.', 'AU-08–12 · AU-18'],
  ['Human', 'Signs up the same way and waits for approval.', 'AU-13–17 · AU-18'],
  ['Admin', 'Reviews each account. Approve → Active. Deny → owner sees the reason, fixes and resubmits.', 'AU-22–26'],
  ['Pet', 'Completes the résumé. Status becomes Looking for a Home; appears in search and matches.', 'PR-03–10'],
  ['Human', 'Completes the Home Profile & quiz, turns on Open to Adopt, gets Pets for You; can bookmark or Invite to Apply.', 'PR-14–20 · MT-01 · RQ-01'],
  ['Pet', 'Opens Homes for You, picks a home, sends an adoption request with a cover letter.', 'MT-02 · RQ-03'],
  ['Human', 'Reviews the request: Approve or Decline. On approval the pet becomes In Process.', 'RQ-11–13'],
  ['Pet', 'Books a Meet & Greet slot. The human confirms or proposes another time.', 'MG-03–06'],
  ['Both', 'Meet in person. When the time has passed, the request moves to Awaiting Decision.', 'MG-07 · MG-08 · MG-11'],
  ['Human', 'Chooses Adopt or Decline. The pet can withdraw any time before this.', 'MG-11 · AL-01 · MG-14'],
  ['System', 'On Adopt: pet Hired and linked, human becomes Furparent, other requests close. On Decline: pet back to Looking for a Home.', 'AL-02–05'],
]

export const CHAINS = [
  { title: 'Account status', main: ['Sign up', 'Pending Verification', 'Active'], side: ['Denied → fix & resubmit → Pending', 'Suspended ↔ Active (admin)', 'Deactivated (owner or admin)'] },
  { title: 'Pet adoption status', main: ['Draft', 'Looking for a Home', 'In Process', 'Adopted — Hired'], side: ['In Process → Looking for a Home when a request ends without adoption', 'Only the system changes it; admins fix issues via Resolve'] },
  { title: 'Adoption request status', main: ['Sent', 'Approved', 'Meet Scheduled', 'Awaiting Decision', 'Adopted'], side: ['On Hold ↔ Sent', 'Declined / Not Adopted', 'Withdrawn', 'Closed / Expired (14 days)'] },
]

export const FRS = [
  ['FR1', 'Human', 'Register and submit verification details; account starts as Pending Verification.'],
  ['FR2', 'Human', 'Log in and use the platform only after approval; pending and denied accounts see a status screen.'],
  ['FR3', 'Human', 'Complete and edit a Home Profile and lifestyle quiz.'],
  ['FR4', 'Human', 'Turn Open to Adopt on or off.'],
  ['FR5', 'Human', 'View a ranked Pets for You feed with match scores and reasons.'],
  ['FR6', 'Human', 'Browse and search pets by species, age, size, temperament and compatibility.'],
  ['FR7', 'Human', 'View a pet’s full résumé.'],
  ['FR8', 'Human', 'Bookmark pet profiles.'],
  ['FR9', 'Human', 'Send an Invite to Apply to a pet.'],
  ['FR10', 'Human', 'Review adoption requests and approve or decline them with an optional message.'],
  ['FR11', 'Human', 'Set Meet & Greet availability; confirm, reschedule or cancel bookings.'],
  ['FR12', 'Human', 'Choose Adopt or Decline once the Meet & Greet time has passed.'],
  ['FR13', 'Human', 'Automatically receive the Furparent label; adopted pets shown on the profile.'],
  ['FR14', 'Human', 'Furparent views the alumni profile and adoption details, and posts adoption stories.'],
  ['FR15', 'Human', 'Receive notifications about requests, Meet & Greets, verification and announcements.'],
  ['FR16', 'Human', 'Report a profile, post, comment or account.'],
  ['FR17', 'Human', 'Post in the community feed, react and comment.'],
  ['FR18', 'Pet', 'Register with the caretaker’s verification details; starts as Pending Verification.'],
  ['FR19', 'Pet', 'Log in and use the platform only after admin approval.'],
  ['FR20', 'Pet', 'Create and edit the résumé: photos, bio, temperament, skills, compatibility, health.'],
  ['FR21', 'Pet', 'View a ranked Homes for You list of humans who are Open to Adopt.'],
  ['FR22', 'Pet', 'Browse and search Home Profiles (public details only).'],
  ['FR23', 'Pet', 'Bookmark Home Profiles.'],
  ['FR24', 'Pet', 'Send an adoption request with a cover letter and track its status.'],
  ['FR25', 'Pet', 'Withdraw a request any time before the final decision.'],
  ['FR26', 'Pet', 'Book, reschedule or cancel a Meet & Greet once a request is approved.'],
  ['FR27', 'Pet', 'Adoption status is changed only by the system, never by hand.'],
  ['FR28', 'Pet', 'On adoption: alumni profile with Hired badge linked to the Furparent; other requests close.'],
  ['FR29', 'Pet', 'Post updates to the community feed, including after adoption.'],
  ['FR30', 'Pet', 'View stats: profile views, bookmarks and request history.'],
  ['FR31', 'Pet', 'Receive notifications about invites, requests, Meet & Greets and verification.'],
  ['FR32', 'Pet', 'Report a profile, post, comment or account.'],
  ['FR33', 'Admin', 'Review the verification queue; approve or deny each account with a reason.'],
  ['FR34', 'Admin', 'Suspend, reactivate or deactivate any account.'],
  ['FR35', 'Admin', 'Review reports; remove, restore or dismiss content or accounts.'],
  ['FR36', 'Admin', 'Monitor all adoption requests and Meet & Greets, including overdue ones.'],
  ['FR37', 'Admin', 'Resolve adoption issues with a required, logged reason.'],
  ['FR38', 'Admin', 'Manage and monitor alumni profiles.'],
  ['FR39', 'Admin', 'Publish platform announcements and notifications.'],
  ['FR40', 'Admin', 'View the platform analytics dashboard.'],
  ['FR41', 'Admin', 'View activity logs of important actions.'],
]

export const NFRS = [
  ['NFR1', 'Usability', 'Long forms are wizards with a progress indicator.', 'AU-08–17 · PR-03–08 · PR-14–19'],
  ['NFR2', 'Security', 'Blocked accounts get status screens only; navigation differs per role.', 'AU-18–21 · GN-01 · AN-03'],
  ['NFR3', 'Data integrity', 'Actions appear only when the rules allow them; no status dropdown.', 'MG-03 · MG-11 · RQ-05 · RQ-06 · PR-01'],
  ['NFR4', 'Privacy', 'City-only Home Profiles; contacts unlocked after confirmation; documents admin-only.', 'DS-07 · MG-07 · AU-23'],
  ['NFR5', 'Availability', 'Not a UI concern — hosting and deployment.', '—'],
  ['NFR6', 'Scalability', 'Screens leave room for shelter accounts and messaging (future scope).', '—'],
  ['NFR7', 'Performance', 'Images compressed on upload; long lists are paginated.', 'PR-09 · DS-01'],
  ['NFR8', 'Compatibility', 'This document shows desktop layouts only; the same components reflow on mobile.', 'All'],
  ['NFR9', 'Accountability', 'Admin actions require a reason and are logged.', 'AU-25 · AC-08 · AL-08 · RP-05 · LG-03–04'],
]
